const { EmbedBuilder } = require("discord.js");
const User = require("../../models/User");
const parseAmount = require("../../utils/numberParser");
const isDeveloper = require("../../utils/isDeveloper");

module.exports = {
  name: "mintcredits",
  aliases: ["generatecredits"],

  async execute(message, args) {
    if (!isDeveloper(message.author.id)) {
      return message.reply("❌ You don't have permission to use this command.");
    }

    const target =
      message.mentions.users.first() ||
      (args[0]
        ? await message.client.users.fetch(args[0]).catch(() => null)
        : null);

    if (!target) {
      return message.reply(
        "❌ Please mention a user or provide their Discord ID."
      );
    }

    if (target.bot) {
      return message.reply("❌ You can't generate Credits for a bot.");
    }

    const amount = parseAmount(args[1]);

    if (amount === null || amount <= 0n) {
      return message.reply(
        "❌ Please enter a valid amount. Example: `,mintcredits @user 100`"
      );
    }

    let user = await User.findOne({
      userId: target.id
    });

    if (!user) {
      user = await User.create({
        userId: target.id
      });
    }

    const oldCredits = BigInt(user.credits || "0");
    const newCredits = oldCredits + amount;

    user.credits = newCredits.toString();

    await user.save();

    console.log(
      `[MINT CREDITS] Developer: ${message.author.id} | ` +
      `Target: ${target.id} | ` +
      `Amount: ${amount.toString()} | ` +
      `Timestamp: ${new Date().toISOString()}`
    );

    const embed = new EmbedBuilder()
      .setTitle("🪙 Credits Generated")
      .setDescription(
        `Successfully generated Credits for **${target.username}**.\n\n` +
        `🪙 Generated: **${amount.toLocaleString()} Credits**\n` +
        `🪙 New Balance: **${newCredits.toLocaleString()} Credits**`
      )
      .setColor(0x2b2d31)
      .setFooter({
        text: `Generated by ${message.author.tag}`
      })
      .setTimestamp();

    await message.reply({
      embeds: [embed]
    });
  }
};