const { EmbedBuilder } = require("discord.js");
const User = require("../../models/User");
const parseAmount = require("../../utils/numberParser");
const isDeveloper = require("../../utils/isDeveloper");

module.exports = {
  name: "mintmoney",
  aliases: ["generatemoney"],

  async execute(message, args) {
    if (!isDeveloper(message.author.id)) {
      return message.reply("❌ You don't have permission to use this command.");
    }

    const target =
      message.mentions.users.first() ||
      (args[0]
        ? await message.client.users.fetch(args[0]).catch(() => null)
        : null);

    if (!target) {
      return message.reply(
        "❌ Please mention a user or provide their Discord ID."
      );
    }

    if (target.bot) {
      return message.reply("❌ You can't generate money for a bot.");
    }

    const amountInput = message.mentions.users.first()
      ? args[1]
      : args[1];

    const amount = parseAmount(amountInput);

    if (amount === null || amount <= 0n) {
      return message.reply(
        "❌ Please enter a valid amount. Example: `,mintmoney @user 1m`"
      );
    }

    let user = await User.findOne({
      userId: target.id
    });

    if (!user) {
      user = await User.create({
        userId: target.id
      });
    }

    const oldWallet = BigInt(user.wallet || "0");
    const newWallet = oldWallet + amount;

    user.wallet = newWallet.toString();

    await user.save();

    console.log(
      `[MINT MONEY] Developer: ${message.author.id} | ` +
      `Target: ${target.id} | ` +
      `Amount: ${amount.toString()} | ` +
      `Timestamp: ${new Date().toISOString()}`
    );

    const embed = new EmbedBuilder()
      .setTitle("💵 Money Generated")
      .setDescription(
        `Successfully generated money for **${target.username}**.\n\n` +
        `💵 Generated: **$${amount.toLocaleString()}**\n` +
        `💰 New Wallet: **$${newWallet.toLocaleString()}**`
      )
      .setColor(0x2b2d31)
      .setFooter({
        text: `Generated by ${message.author.tag}`
      })
      .setTimestamp();

    await message.reply({
      embeds: [embed]
    });
  }
};